services:
  Bank.Account.domain.AccountRepository:
    class: ../../../Bank/Account/infrastructure/persistence/InMemoryAccountRepository

  Bank.Account.application.DepositRegisterer:
    class: ../../../Bank/Account/application/DepositRegisterer
    arguments: ['@Bank.Account.domain.AccountRepository', '@Shared.domain.EventBus']

  Bank.Account.application.WithdrawalRegisterer:
    class: ../../../Bank/Account/application/WithdrawalRegisterer
    arguments: ['@Bank.Account.domain.AccountRepository', '@Shared.domain.EventBus']

  Bank.Account.application.TransferExecutor:
    class: ../../../Bank/Account/application/TransferExecutor
    arguments: ['@Bank.Account.domain.AccountRepository', '@Shared.domain.EventBus']