services:
  App.controllers.DepositPostController:
    class: ../../controllers/DepositPostController
    arguments: ['@Bank.Account.application.DepositRegisterer']
  App.controllers.WithdrawalPostController:
    class: ../../controllers/WithdrawalPostController
    arguments: ['@Bank.Account.application.WithdrawalRegisterer']
  App.controllers.TransferPostController:
    class: ../../controllers/TransferPostController
    arguments: ['@Bank.Account.application.TransferExecutor']